from .appointments import APPOINTMENT_BLUEPRINT
from .available_appointment_date import AVAILABLE_APPOINTMENT_DATE_BLUEPRINT
from .available_appointment_time import AVAILABLE_APPOINTMENT_TIME_BLUEPRINT
from .doctor import DOCTOR_BLUEPRINT
from .hospital import HOSPITAL_BLUEPRINT
from .image_test import IMAGE_TEST_BLUEPRINT
from .news import NEWS_BLUEPRINT
from .polyclinic import POLYCLINIC_BLUEPRINT
from .profession import PROFESSION_BLUEPRINT
from .patient_test import PATIENT_TEST_BLUEPRINT
