from .appointments import APPOINTMENT_BLUEPRINT
from .available_date import AVAILABLE_APPOINTMENT_DATE_BLUEPRINT
from .available_hour import AVAILABLE_APPOINTMENT_TIME_BLUEPRINT
from .doctor import DOCTOR_BLUEPRINT
from .hospital import HOSPITAL_BLUEPRINT
from .news import NEWS_BLUEPRINT
from .polyclinic import POLYCLINIC_BLUEPRINT
from .profession import PROFESSION_BLUEPRINT
from .patient import PATIENT_BLUEPRINT
